SRC = $(wildcard *.cpp)
OBJS = $(patsubst %.cpp,%.obj,$(SRC))
CXX = cl /nologo
CXXFLAG = /D_WIN32 /D_DEBUG /Od /Zi /Iinclude /c
DIRECTSDK := "D:\Program Files\Microsoft DirectX SDK (June 2010)\Include"
dream.exe:$(OBJS)

%.obj:%.cpp
	$(CXX) $(CXXFLAG) /I$(DIRECTSDK) /Fo$@ $<
	
clean:
	-del $(OBJS)
	-del *.pdb